"""add api_key_rotated_at to projects

Revision ID: 588f1582159e
Revises: 6661ea030fd0
Create Date: 2026-09-28 19:15:06.039122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588f1582159e'
down_revision: Union[str, Sequence[str], None] = '6661ea030fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('api_key_rotated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'api_key_rotated_at')
    # ### end Alembic commands ###
